config/routes.rb
Catalog::Application.routes.draw do
  
  resources :collections

  root :to => 'people#index'
  resources :emails
  resources :inhabitants
  resources :phones
  resources :people
  resources :addresses, :only => [:index, :new, :create, :destroy, :edit, :show, :update]
  resources :users
  

  get 'register', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'
  resources :sessions, :only => [:new, :create, :destroy]
  

  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection = Collection.find(params[:id])
    @users = User.all
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = Collection.new
    @users = User.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
    @users = User.all

  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(params[:collection])
    @users = User.all

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render json: @collection, status: :created, location: @collection }
      else
        format.html { render action: "new" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = Collection.find(params[:id])
    @users = User.all

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.select :user_id, options_from_collection_for_select(@users, :id, :to_s, 
        selected_key = current_user.id)%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h1>Listing collections</h1>
<p> <% if current_user.nil? %>
          no user signed in
    <% else %>
          <%= pluralize(current_user.collections.count, 'collection') %>
    <% end %>
</p>


<% if not current_user.collections.empty? %>

    <table>
      <tr>
        <th>Name</th>
        <th>User</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% current_user.collections.each do |collection| %>
          <tr>
            <td><%= collection.name %></td>
            <td><%= collection.user_id %></td>
            <td><%= link_to 'Show', collection %></td>
            <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
            <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    </table>
    <%= link_to 'New Collection', new_collection_path %>
<% end %>
<br />

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p>
  <b>Name:</b>
  <%= @collection.name %>
</p>

<p>
  <b>User:</b>
  <%= @collection.user_id %>
</p>


<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>