config/routes.rb
Catalog::Application.routes.draw do
  
  resources :collections

  root :to => 'people#index'
  resources :emails
  resources :inhabitants
  resources :phones
  resources :people
  resources :addresses, :only => [:index, :new, :create, :destroy, :edit, :show, :update]
  resources :users
  

  get 'register', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'
  resources :sessions, :only => [:new, :create, :destroy]
  

  

end

app/models/inhabitant.rb
class Inhabitant < ActiveRecord::Base
  attr_accessible :address_id, :person_id
  belongs_to :address
  belongs_to :person

  validates :address_id, uniqueness: {scope: :person_id, message: "already added to this person"}

end

app/controllers/inhabitants_controller.rb
class InhabitantsController < ApplicationController
  # GET /inhabitants
  # GET /inhabitants.json
  def index
    @inhabitants = Inhabitant.order("person_id")
    #@inhabitants = Inhabitant.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inhabitants }
    end
  end

  # GET /inhabitants/1
  # GET /inhabitants/1.json
  def show
    @inhabitant = Inhabitant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inhabitant }
    end
  end

  # GET /inhabitants/new
  # GET /inhabitants/new.json
  def new
    @inhabitant = Inhabitant.new
    @people = Person.all
    @addresses = Address.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inhabitant }
    end
  end

  # GET /inhabitants/1/edit
  def edit
    @inhabitant = Inhabitant.find(params[:id])
    @people = Person.all
    @addresses = Address.all
  end

  # POST /inhabitants
  # POST /inhabitants.json
  def create
    @inhabitant = Inhabitant.new(params[:inhabitant])
    @people = Person.all
    @addresses = Address.all

    respond_to do |format|
      if @inhabitant.save
        format.html { redirect_to @inhabitant, notice: 'Inhabitant was successfully created.' }
        format.json { render json: @inhabitant, status: :created, location: @inhabitant }
      else
        format.html { render action: "new" }
        format.json { render json: @inhabitant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inhabitants/1
  # PUT /inhabitants/1.json
  def update
    @inhabitant = Inhabitant.find(params[:id])
    @people = Person.all
    @addresses = Address.all

    respond_to do |format|
      if @inhabitant.update_attributes(params[:inhabitant])
        format.html { redirect_to @inhabitant, notice: 'Inhabitant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inhabitant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inhabitants/1
  # DELETE /inhabitants/1.json
  def destroy
    @inhabitant = Inhabitant.find(params[:id])
    @inhabitant.destroy

    respond_to do |format|
      format.html { redirect_to inhabitants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/inhabitants_helper.rb
module InhabitantsHelper
end

app/views/inhabitants/_form.html.erb
<%= form_for(@inhabitant) do |f| %>
  <% if @inhabitant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inhabitant.errors.count, "error") %> prohibited this inhabitant from being saved:</h2>

      <ul>
      <% @inhabitant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.select :person_id, options_from_collection_for_select(@people, :id, :to_s, 
        selected_key = @inhabitant.person_id)%>
  </div>
  <div class="field">
    <%= f.label :address_id %><br />
    <%= f.select :address_id, options_from_collection_for_select(@addresses, :id, :to_s, 
        selected_key = @inhabitant.address_id)%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inhabitants/edit.html.erb
<h1>Editing inhabitant</h1>

<%= render 'form' %>

<%= link_to 'Show', @inhabitant %> |
<%= link_to 'Back', inhabitants_path %>

app/views/inhabitants/index.html.erb
<h1>Listing inhabitants</h1>

<table>
  <tr>
    <th>Person</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inhabitants.each do |inhabitant| %>
  <tr>
    <td><%= inhabitant.person %></td>
    <td><%= inhabitant.address %></td>
    <td><%= link_to 'Show', inhabitant %></td>
    <td><%= link_to 'Edit', edit_inhabitant_path(inhabitant) %></td>
    <td><%= link_to 'Destroy', inhabitant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inhabitant', new_inhabitant_path %>

app/views/inhabitants/new.html.erb
<h1>New inhabitant</h1>

<%= render 'form' %>

<%= link_to 'Back', inhabitants_path %>

app/views/inhabitants/show.html.erb
<p>
  <b>Person:</b>
  <%= @inhabitant.person %>
</p>

<p>
  <b>Address:</b>
  <%= @inhabitant.address %>
</p>


<%= link_to 'Edit', edit_inhabitant_path(@inhabitant) %> |
<%= link_to 'Back', inhabitants_path %>